name: 'My Custom Action'
description: 'Test'
author: 'zv'
inputs:
  secretname:
    decription: 'name of the secret'
    required: true


# runs:
#   using: 'node20'
#   main: 'dist/index.js'
runs:
  using: "composite"
  steps:
    - name: My first step
      uses: actions/checkout@v2
    
    - name: run program
      run: node ./dist/index.js 
      