name: 'My Custom Action'
description: 'Test'
author: 'zv'
inputs:
  secretname:
    decription: 'name of the secret'
    required: true
outputs:
  secretname:
    value: ${{ steps.export-secret.outputs.username }} 
  secretPassword:
    value: ${{steps.export-secret.outputs.password}}     


# runs:
#   using: 'node20'
#   main: 'dist/index.js'
runs:
  using: "composite"
  steps:
    - name: My first step
      uses: actions/checkout@v2
    
    - name: run program
      run: node ./dist/index.js 
      shell: bash

    - name: export secret
      id: export-secret
      run: |
           echo "username=$secretUsername" >> $GITHUB_OUTPUT
           echo "password=$secretPassword" >> $GITHUB_OUTPUT 
       
      shell: bash
      